[package]
name = "ya-self-test-gpu"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ya-self-test-gpu"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
parse-size = "1.0.0"
roxmltree = "0.18.0"
serde_json = "1.0"
