[package]
name = "ya-self-test-gpu"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
golem-gpu-info = { git = "https://github.com/golemfactory/golem-gpu-info.git", branch = "feature/multi-gpu"}
serde_json = "1.0"
