name: Release

on:
  push:
    tags:
      - v*
      - pre-rel-*

env:
  rust_stable: 1.70.0
  gvmkit-build_tag: v0.3.1
  gvmkit-build_dir: gvmkit-build
  gvmkit-build_archive: gvmkit-build-x86_64-unknown-linux-gnu.tar.gz
  dist_dir: dist
  dist_img: self-test.gvmi
  self-test-img_tag: self-test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ env.self-test-img_tag }}
        
      - name: Download gvmkit-build
        uses: robinraju/release-downloader@v1.8
        with:
          repository: golemfactory/gvmkit-build-rs
          tag: ${{ env.self-test-img_tag }}
          fileName: ${{ env.gvmkit-build_archive }}
          extract: true
          out-file-path: ${{ env.gvmkit-build_dir }}
          tarBall: false
          zipBall: false

      - name: Build GVMkit image
        run: |
          mkdir ${{ env.dist_dir }}
          ${{ env.gvmkit-build_dir }}/gvmkit-build ${{ env.self-test-img_tag }}:latest -o ${{ env.dist-dir }}/${{ env.dist_img }} --push false

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          files: ${{ env.dist-dir }}/${{ env.dist_img }}
